### PR TITLE
Add more uncountable words

### PR DESCRIPTION
**Pull request by hkdobrev**
Here is a list of the new ones:

- ~~access~~
- aircraft
- ~~bison~~
- ~~dance~~
- deer
- ~~fuel~~
- ~~heat~~
- ~~honey~~
- ~~media~~
- moose
- music
- news
- ~~pollution~~
- salmon
- sand
- sms
- spam
- swine
- traffic
- ~~understanding~~
- ~~water~~

### CODE REVIEW

**Comment by olvlvl** [comment]
Thanks for your contribution. I came up with this list. What do you think?

- [ ] `access` => `accesses` (countable and uncountable) https://en.wiktionary.org/wiki/access
- [x] `aircraft`
- [ ] `bison` => `bisons` (usually uncountable) https://en.wiktionary.org/wiki/bison
- [ ] `dance` => `dances` https://en.wiktionary.org/wiki/dance
- [x] `deer` https://en.wiktionary.org/wiki/deer
- [ ] `fuel` => `fuels` (countable and uncountable) https://en.wiktionary.org/wiki/fuel
- [ ] `heat` => `heats` (countable and uncountable) https://en.wiktionary.org/wiki/heat
- [ ] `honey` (usually uncountable, plural `honeys`) https://en.wiktionary.org/wiki/honey
- [ ] `media` is tricky https://en.wiktionary.org/wiki/media
- [x] `moose` https://en.wiktionary.org/wiki/moose
- [x] `music` https://en.wiktionary.org/wiki/music
- [x] `news` https://en.wiktionary.org/wiki/news
- [ ] `pollution` => `pollutions` https://en.wiktionary.org/wiki/pollution
- [x] `salmon` https://en.wiktionary.org/wiki/salmon
- [x] `sand` https://en.wiktionary.org/wiki/sand
- [x] `sms` https://en.wiktionary.org/wiki/sms
- [x] `spam` https://en.wiktionary.org/wiki/spam
- [x] `swine` https://en.wiktionary.org/wiki/swine
- [x] `traffic` https://en.wiktionary.org/wiki/traffic
- [ ] `understanding` (countable and uncountable, plural understandings) https://en.wiktionary.org/wiki/understanding
- [ ] `water` (countable and uncountable, plural waters) https://en.wiktionary.org/wiki/water

**Comment by hkdobrev** [comment]
@olvlvl Thanks for looking into those so closely! I am basically trying to contribute what the Kohana inflector had and removed a few myself.

I've already removed `media`.

I'll agree with the above, but I'm really struggling with `water`. For me `waters` is, of course, a valid word, but it's completely different word. It's not the plural of `water`.

**Comment by hkdobrev** [comment]
`media` is also quite tricky. When you want the plural of `medium` - that's `media`, but the singular of `media` is not always `medium`, depending on context.

**Comment by hkdobrev** [comment]
@olvlvl Updated ✅

**Comment by olvlvl** [comment]
Thanks! Please update the tests with the new uncountable.

**Comment by hkdobrev** [comment]
@olvlvl Done! ✅

**Comment by hkdobrev** [comment]
🙌

**Pull request merged**
